🚧 Update to SDK 27.25.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
👨🏾‍🦼💆🏼‍♀️⛺️🚶🏽

Full error log:
Error:  asset 2022-9-3--3-13-44--1bbe04a8-b151-4624-8548-a06718114f07/main.min.js 580 KiB [emitted] (name: main) 1 related asset
asset 2022-9-3--3-13-44--1bbe04a8-b151-4624-8548-a06718114f07/vendors-node_modules_canvg_lib_index_es_js.main.min.js 462 KiB [emitted] (id hint: vendors) 1 related asset
asset 2022-9-3--3-13-44--1bbe04a8-b151-4624-8548-a06718114f07/vendors-node_modules_html2canvas_dist_html2canvas_js.main.min.js 431 KiB [emitted] (id hint: vendors) 1 related asset
asset 2022-9-3--3-13-44--1bbe04a8-b151-4624-8548-a06718114f07/vendors-node_modules_dompurify_dist_purify_js.main.min.js 60.6 KiB [emitted] (id hint: vendors) 1 related asset
runtime modules 7.05 KiB 10 modules
modules by path ./node_modules/core-js/internals/*.js 92.3 KiB 135 modules
modules by path ./node_modules/core-js/modules/*.js 41 KiB 21 modules
modules by path ./src/ 26.7 KiB
modules by path ./src/modules/ 13.1 KiB 5 modules
modules by path ./src/utils/*.ts 8.84 KiB 4 modules
modules by path ./src/components/*.tsx 4.37 KiB
./src/components/PrintComponent.tsx 2.4 KiB [built] [code generated] [1 error]
./src/components/PdfComponent.tsx 1.97 KiB [built] [code generated]
./src/index.ts 348 bytes [built] [code generated]
modules by path ./node_modules/@babel/runtime/helpers/esm/*.js 1.39 KiB
./node_modules/@babel/runtime/helpers/esm/typeof.js 368 bytes [built] [code generated]
./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js 787 bytes [built] [code generated]
./node_modules/@babel/runtime/helpers/esm/defineProperty.js 269 bytes [built] [code generated]
13 modules

ERROR in C:\Users\me\work\collboard\pdf-support\src\components\PrintComponent.tsx
./src/components/PrintComponent.tsx 3:4-16
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\components\PrintComponent.tsx(3,5)
TS2305: Module '"@collboard/modules-sdk"' has no exported member 'downloadFile'.
@ ./src/modules/print-module.tsx 14:25-64
@ ./src/index.ts 6:0-33

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts
./src/modules/pdf-import-module.ts 3:4-17
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts(3,5)
TS2724: '"@collboard/modules-sdk"' has no exported member named 'blobToDataUrl'. Did you mean 'blobToDataurl'?
@ ./src/index.ts 4:0-38

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts
./src/modules/pdf-import-module.ts 5:4-17
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts(5,5)
TS2724: '"@collboard/modules-sdk"' has no exported member named 'dataUrlToBlob'. Did you mean 'dataurlToBlob'?
@ ./src/index.ts 4:0-38

ERROR in C:\Users\me\work\collboard\pdf-support\src\utils\createPdf.ts
./src/utils/createPdf.ts 1:9-22
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\utils\createPdf.ts(1,10)
TS2724: '"@collboard/modules-sdk"' has no exported member named 'blobToDataUrl'. Did you mean 'blobToDataurl'?
@ ./src/modules/pdf-export-module.ts 14:20-49
@ ./src/index.ts 3:0-38

webpack 5.35.1 compiled with 4 errors in 8034 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\pdf-support\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\lib\Watching.js:201:28)