🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🐵💇🏾‍♂️🥬👨🏿‍🦲

Full error log:
Error:  asset 2022-7-25--0-32-15--0993d561-b6a8-44ab-8f73-9e8bf94d63df/main.min.js 550 KiB [emitted] (name: main) 1 related asset
asset 2022-7-25--0-32-15--0993d561-b6a8-44ab-8f73-9e8bf94d63df/vendors-node_modules_canvg_lib_index_es_js.main.min.js 462 KiB [emitted] (id hint: vendors) 1 related asset
asset 2022-7-25--0-32-15--0993d561-b6a8-44ab-8f73-9e8bf94d63df/vendors-node_modules_html2canvas_dist_html2canvas_js.main.min.js 431 KiB [emitted] (id hint: vendors) 1 related asset
asset 2022-7-25--0-32-15--0993d561-b6a8-44ab-8f73-9e8bf94d63df/vendors-node_modules_dompurify_dist_purify_js.main.min.js 60.6 KiB [emitted] (id hint: vendors) 1 related asset
runtime modules 7.05 KiB 10 modules
modules by path ./node_modules/core-js/internals/*.js 92.3 KiB 135 modules
modules by path ./node_modules/core-js/modules/*.js 41 KiB 21 modules
modules by path ./src/ 26.6 KiB
modules by path ./src/modules/ 13.1 KiB 5 modules
modules by path ./src/utils/*.ts 8.84 KiB 4 modules
modules by path ./src/components/*.tsx 4.37 KiB
./src/components/PrintComponent.tsx 2.4 KiB [built] [code generated]
./src/components/PdfComponent.tsx 1.97 KiB [built] [code generated]
./src/index.ts 348 bytes [built] [code generated]
modules by path ./node_modules/@babel/runtime/helpers/esm/*.js 1.39 KiB
./node_modules/@babel/runtime/helpers/esm/typeof.js 368 bytes [built] [code generated]
./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js 787 bytes [built] [code generated]
./node_modules/@babel/runtime/helpers/esm/defineProperty.js 269 bytes [built] [code generated]
13 modules

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts
./src/modules/pdf-import-module.ts 64:107-112
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts(64,108)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.
@ ./src/index.ts 4:0-38

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts
./src/modules/pdf-import-module.ts 65:48-58
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts(65,49)
TS2339: Property 'windowSize' does not exist on type 'AppState'.
@ ./src/index.ts 4:0-38

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts
./src/modules/pdf-import-module.ts 65:85-90
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts(65,86)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.
@ ./src/index.ts 4:0-38

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts
./src/modules/pdf-import-module.ts 73:47-52
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts(73,48)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.
@ ./src/index.ts 4:0-38

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts
./src/modules/pdf-import-module.ts 89:76-81
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\pdf-import-module.ts(89,77)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.
@ ./src/index.ts 4:0-38

webpack 5.35.1 compiled with 5 errors in 8326 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\pdf-support\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\lib\Watching.js:201:28)