🚧 Update to SDK 34.3.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🌧✌🏿☮️🍙

Full error log:
Error:  asset 2023-1-20--11-5-9--0a5b6843-c9db-4ca6-a75b-fd1fa6ba86b3/main.min.js 587 KiB [emitted] (name: main) 1 related asset
asset 2023-1-20--11-5-9--0a5b6843-c9db-4ca6-a75b-fd1fa6ba86b3/vendors-node_modules_canvg_lib_index_es_js.main.min.js 462 KiB [emitted] (id hint: vendors) 1 related asset
asset 2023-1-20--11-5-9--0a5b6843-c9db-4ca6-a75b-fd1fa6ba86b3/vendors-node_modules_html2canvas_dist_html2canvas_js.main.min.js 431 KiB [emitted] (id hint: vendors) 1 related asset
asset 2023-1-20--11-5-9--0a5b6843-c9db-4ca6-a75b-fd1fa6ba86b3/vendors-node_modules_dompurify_dist_purify_js.main.min.js 60.6 KiB [emitted] (id hint: vendors) 1 related asset
runtime modules 7.05 KiB 10 modules
modules by path ./node_modules/core-js/internals/*.js 92.3 KiB 135 modules
modules by path ./node_modules/core-js/modules/*.js 41 KiB 21 modules
modules by path ./src/ 26.7 KiB
  modules by path ./src/modules/ 13.2 KiB 5 modules
  modules by path ./src/utils/*.ts 8.84 KiB 4 modules
  modules by path ./src/components/*.tsx 4.38 KiB
    ./src/components/PrintComponent.tsx 2.41 KiB [built] [code generated]
    ./src/components/PdfComponent.tsx 1.97 KiB [built] [code generated]
  ./src/index.ts 348 bytes [built] [code generated]
modules by path ./node_modules/@babel/runtime/helpers/esm/*.js 1.39 KiB
  ./node_modules/@babel/runtime/helpers/esm/typeof.js 368 bytes [built] [code generated]
  ./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js 787 bytes [built] [code generated]
  ./node_modules/@babel/runtime/helpers/esm/defineProperty.js 269 bytes [built] [code generated]
13 modules

ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\print-shortcut-module.ts
./src/modules/print-shortcut-module.ts 23:54-80
[tsl] ERROR in C:\Users\me\work\collboard\pdf-support\src\modules\print-shortcut-module.ts(23,55)
      TS2345: Argument of type '{ module: string; modulePath: null; }' is not assignable to parameter of type 'Partial<RemoveIndex<IUrlVariables>>'.
  Object literal may only specify known properties, and 'module' does not exist in type 'Partial<RemoveIndex<IUrlVariables>>'.
 @ ./src/index.ts 8:0-42

webpack 5.35.1 compiled with 1 error in 7488 ms

Error:
    at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:89:37)
    at Generator.next (<anonymous>)
    at C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
    at Watching.handler (C:\Users\me\work\collboard\pdf-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:83:72)
    at C:\Users\me\work\collboard\pdf-support\node_modules\webpack\lib\Watching.js:204:9
    at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (C:\Users\me\work\collboard\pdf-support\node_modules\webpack\lib\Watching.js:201:28)